import {
  AbsoluteFill,
  interpolate,
  spring,
  useCurrentFrame,
  useVideoConfig,
} from 'remotion';

interface EndCardProps {
  summaryPoints: string[];
  teaserNextEpisode: string | null;
  seriesTitle: string;
}

export const EndCard: React.FC<EndCardProps> = ({
  summaryPoints,
  teaserNextEpisode,
  seriesTitle,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  // Fade in
  const containerOpacity = interpolate(frame, [0, 15], [0, 1], {
    extrapolateRight: 'clamp',
  });

  return (
    <AbsoluteFill
      style={{
        background: 'linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%)',
        opacity: containerOpacity,
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        justifyContent: 'center',
        padding: '60px 80px',
      }}
    >
      {/* Title */}
      <div
        style={{
          fontSize: 36,
          fontWeight: 700,
          color: '#e0e0e0',
          marginBottom: 40,
          fontFamily: "'Noto Sans', sans-serif",
        }}
      >
        What you learned today:
      </div>

      {/* Summary points */}
      <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
        {summaryPoints.map((point, i) => {
          const pointAppear = spring({
            frame: frame - 30 - i * 20,
            fps,
            config: { damping: 12, stiffness: 100 },
          });

          return (
            <div
              key={i}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: 16,
                opacity: pointAppear,
                transform: `translateX(${(1 - pointAppear) * 50}px)`,
              }}
            >
              <div
                style={{
                  width: 32,
                  height: 32,
                  borderRadius: '50%',
                  background: '#4ade80',
                  display: 'flex',
                  alignItems: 'center',
                  justifyContent: 'center',
                  fontSize: 18,
                  color: '#1a1a2e',
                  fontWeight: 700,
                  flexShrink: 0,
                }}
              >
                ✓
              </div>
              <div
                style={{
                  fontSize: 22,
                  color: '#f0f0f0',
                  fontFamily: "'Noto Sans', sans-serif",
                  lineHeight: 1.4,
                }}
              >
                {point}
              </div>
            </div>
          );
        })}
      </div>

      {/* Teaser */}
      {teaserNextEpisode ? (
        <div
          style={{
            marginTop: 50,
            opacity: interpolate(
              frame,
              [30 + summaryPoints.length * 20 + 20, 30 + summaryPoints.length * 20 + 40],
              [0, 1],
              { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' },
            ),
          }}
        >
          <div
            style={{
              fontSize: 18,
              color: '#a0a0a0',
              fontStyle: 'italic',
              fontFamily: "'Noto Sans', sans-serif",
            }}
          >
            Next episode: {teaserNextEpisode}
          </div>
        </div>
      ) : null}

      {/* Logo */}
      <div
        style={{
          position: 'absolute',
          bottom: 40,
          display: 'flex',
          alignItems: 'center',
          gap: 8,
          opacity: 0.6,
        }}
      >
        <div
          style={{
            fontSize: 16,
            color: '#888',
            fontFamily: "'Noto Sans', sans-serif",
          }}
        >
          {seriesTitle} — Generated by AnimeLearn
        </div>
      </div>
    </AbsoluteFill>
  );
};
